
engines:
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  csslint:
    enabled: true
  coffeelint:
    enabled: true
    checks:
      max_line_length:
        enabled: false
  duplication:
    enabled: true
    checks:
      Similar code:
        enabled: false
    config:
      languages:
      - ruby
      - javascript
  eslint:
    enabled: true
  fixme:
    enabled: true
  rubocop:
    enabled: true
ratings:
  paths:
  - Gemfile.lock
  - "**.erb"
  - "**.haml"
  - "**.rb"
  - "**.slim"
  - "**.css"
  - "**.js"
exclude_paths:
