language: node_js
node_js:
  - "6"
cache:
  bundler: true
  yarn: true
  directories:
  - node_modules
before_script:
- npm run generate
after_success:
- npm run coveralls
notifications:
  email: false
