language: ruby
rvm:
- 2.2
branches:
  only:
  - source
  - master
cache:
- bundler
gemfile: travisGemfile
install:
- bundle install
before_script:
- git config credential.helper "store --file=.git/credentials"
- echo "https://${GH_TOKEN}:@github.com" > .git/credentials
- git config --global user.email "nandomoreira.me@gmail.com"
- git config --global user.name "Fernando Moreira"
- rake deploy
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - GH_USER="Fernando Moreira"
  - GH_EMAIL="nandomoreira.me@gmail.com"
  - GH_REF="nandomoreirame/nandomoreirame.github.io"
  - HTML_FOLDER="./build/"
  - secure: P3f8Pdx8pdaGRrOcYyQXfxoBJGFLIniis6ZjFrHK6Lzqu/6jpkODfJivUYzULWChVCp2D9JLLaM4bsdU2HcwJHW/ASxMa3SmXOAqEtoiiFNmSAt85GW/1O+O8V62DNFwbqnGaqrL/o4ytwq7oHDJk/kMU04AzpQgXXhCTEiFyadDAu2/LDe4cPrhwl+QEzlNWsnVx/LXIiksD9BLbKCKtlK96xDlNdF+b84kNOzilzDUsof5XG70TX9Rr149F8WTBclTZIIrzgFy8EfugQS/qRtOwu7YbSpMq/YaeDZZozoZ8wkvopLX2poNYoMGLkjF+xgQR5c5tBTIqk5gjv55lB6uOuohuhM/y+wTg8h6tZz3YZSJB+GsPskRuso+L7w+uPRXpL8MmjOmjIvf01zDmJ981K3txZIgOBUKKImnR6o3guLsMEQsqmgcXHidsqEvyM4h/bERZVOpfDTk766g8UO4pFHuxFwg6gbBdthcdSCFuNWJ3Fs16InQ1mNW+6nJ/xsFU357RjsbaSambxDGkWxKiwoJFXmeF6LIeIR81mUK+765kulYbqZqZKo2jOMq0u+3R+iu6I8cPKsh3g2iSOvP8AK8pHXU7xscK/67li/GU5p85ijsoCZ24hpDbdSk2PNSDfp+rZXntwAXkjVKM7YcXKgHMuTE2O/sEELyELw=
notifications:
  email: true
