language: ruby
rvm:
- 2.1
branches:
  only:
  - source
  - master
cache:
- bundler
gemfile: travisGemfile
install:
- bundle install
before_script:
- chmod +x deploy.sh
- git config credential.helper "store --file=.git/credentials"
- echo "https://${GH_TOKEN}:@github.com" > .git/credentials
script: "./deploy.sh"
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - GH_USER="Fernando Moreira"
  - GH_EMAIL="nandomoreira.me@gmail.com"
  - GH_REF="nandomoreirame/nandomoreirame.github.io"
  - HTML_FOLDER="./build/"
  - secure: TSYq7grb97yL+fE7H4Cks1gStnHW3QjNQYmryeniCBWWZupFj1EzPuGVYQl6czC1Gjp42P8g5uIkVtCPLnhXLwGn+iB+J/2stPut5kbbGgR5N+To5NfYq9P9TiBV4V9ffflotSMgUoDAH8Dq28Kdg+lLqf64n3EnfXtW+lJLejWNUxdPjWpcnScpVSAiMFj6a1f37VgZyGKG2tFMTpgdptTLqKRmyWu8fywreoJSjAuuqX+WFS1RNWGiOpCVAaydorHXLi6D4L97uraRArn16CEtA6S9b6WulU3uB/0cQg3kSU+G91XMPAyp4F+FF6GUSLZrJ/UP1CCXegpEIM15S/FsYvwgRF++Wgo63tuhA2xolHJP30iwzgUn3EfrjRIbgonG+fCJOd0LC2gjl8QQhOAS2SpFuuhp7XSmkpLuzg1WTYoUOivDYMsj7RQ3Ch7I89xfjTb+ZBmz/iHSkvNf7dI/2bcjOzBYI5uTF3ooeqw8LlWLJ6podA6ZzRaeGWKD424MujucIEqkJX6VQftx3SECTNZnHvTXuhomNV3Kq71sS8QUiW1vuaDZrpwDIMMrF8bDR1HX17yVj/fB6JTqT1WpVfhnnJTzElEatA4yDLzEukbcWEfYN2SnJec3edsn1tHisl2LQfGLptuckCEvUgCDE06xOiP/1zQhFlRuI3w=
notifications:
  email: true
