language: ruby
rvm:
  - 2.3.1
branches:
  only:
    - source
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
    - GH_USER="Fernando Moreira"
    - GH_EMAIL="nandomoreira.me@gmail.com"
cache: bundler
gemfile: travisGemfile
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y build-essential -qq
  - curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
  - sudo apt-get install -y nodejs -qq
  - nvm -v
  - node -v
install: npm install
script: bundle exec rake travis:script
after_success: bundle exec rake travis:after_success
notifications:
  email: false
