language: ruby
rvm:
  - 2.3.1
node_js:
  - "6.9"
branches:
  only:
    - source
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
    - GH_USER="Fernando Moreira"
    - GH_EMAIL="nandomoreira.me@gmail.com"
cache: bundler
gemfile: travisGemfile
install: npm install
script: bundle exec rake travis:script
after_success: bundle exec rake travis:after_success
notifications:
  email: false
